name: $(Date:yyyy-MM-dd) WebUI-Tests

trigger:
- schedule: cron 0 */2 * * *
  branches:
    include:
    - main  # Замініть це на вашу головну гілку

pr: ubuntu-20.04

pool:
  vmImage: 'ubuntu-latest'
jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UseNode@2
    inputs:
      versionSpec: '18.x'
      addToPath: true
  - script: |
      npm i npm@latest
      npm ci
      npm run test
      npm run allure:generate
    displayName: 'Install, Test, and Generate report'