name: $(Date:yyyy-MM-dd) WebUI-Tests

schedules:
- cron: "0 */2 * * *"
  displayName: 'Run every 2 hours'
  branches:
    include:
    - master  # Replace this with your main branch

trigger: none

pr:
  branches:
    include:
    - master

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: 'ubuntu-20.04'  # Use Ubuntu 20.04 image
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true
  - script: |
      npm install
      npm run test
      npm run allure:generate
    displayName: 'Install, Test, and Generate report'