name: Test and create report

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  Run_test:
    runs-on: ubuntu-20.04 # Choosing OS
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i npm@latest
    - run: npm i
    - name: run test
      run: npm run test
    - name: Create Report
      if: always()
      run: npm run allure:generate
    - name: Upload artifact cucumber-report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: ./allure-report
        retention-days: 5
    - name: Deploy to pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./allure-report